def parse_polynomial(poly_str):
    poly_str = poly_str.replace(" ", "")
    terms = []
    current_term = ""
    
    #iterate every char in the input string
    #enumerate(str): return a pair of (idx,element) in a str
    for i, char in enumerate(poly_str):
        #find a new term
        if char in "+-" and i > 0:
            #add the previous term to the result list
            terms.append(current_term)
            #start a new tern
            current_term = char
        #extend the current term(ex. a term can be extended like 2X^2)
        else:
            current_term += char
    
    #can't find a "+" or "-" in the end of the input, so we need to add the last term to the list here
    terms.append(current_term)
    #the result may be like [2X^2, Y^3, ...]
    return terms

# extract coefficient, variables, and exponents for a single "term" like 2*XY^2
def parse_term(term):
    # 1. deal with the coefficient
    #ex. X^2, +Y^3, -X, ...
    if "*" not in term:
        if term[0] == '-':
            if term[1:].isdigit(): #pure number without variable
                return int(term), {} 
            else:
                coefficient = -1
                variables = term[1:] if len(term) > 1 else ''
        elif term[0] == '+':
            if term[1:].isdigit():
                return int(term), {} 
            else:
                coefficient = 1
                variables = term[1:] if len(term) > 1 else '' 
        else: # a term starts with a letter
            coefficient = 1 if term[0].isalpha() else int(term)
            variables = term if term[0].isalpha() else ''
    #ex. 3*X^2 (split to)=> 3, X^2
    else:
        coefficient_part, variables = term.split("*")
        coefficient = int(coefficient_part)
    
    # 2. deal with variables and their exponents
    # variables: ex. XY^2 (split to)=> var_dict: ex. {X:1, Y:2}
    var_dict = {}
    current_var = ""
    for i, char in enumerate(variables):
        #check if the char is an english letter
        if char.isalpha():
            current_var = char
            var_dict[current_var] = 1
        elif char == "^":
            exp_end_index = i + 1 #start from the begin
            #find the end-index for the digits(exp)
            while (exp_end_index < len(variables)) and (variables[exp_end_index].isdigit()):
                exp_end_index += 1
            var_dict[current_var] = int(variables[i+1: exp_end_index]) if (exp_end_index > i + 1) else 1 #the numbers after "^"
    #print(coefficient)
    return coefficient, var_dict

# multiply two terms
def multiply_terms(term1, term2):
    '''
    term1: 2*Y
    term2: XZ^2
    '''
    #coef: coefficient of a term
    #vars: a dict of the pairs (var:power)
    '''
    coef1: 2, vars1: {Y:1}
    coef2: 1, vars2: {X:1,Z:2}
    '''
    coef1, vars1 = parse_term(term1) 
    coef2, vars2 = parse_term(term2)
    
    '''
    new_coef: 2*1 = 2
    '''
    new_coef = coef1 * coef2
    #init the result vars: dict of the pairs (var:power)
    new_vars = vars1.copy()
    
    #items() => extract each pair of (key:value) in a dict
    '''
    new_vars: {Y:1}
    new_vars: {Y:1,X:1}
    new_vars: {Y:1,X:1,Z:2} => YXZ^2
    '''
    for var, exp in vars2.items():
        if var in new_vars:
            new_vars[var] += exp
        else:
            new_vars[var] = exp
    
    # 2*YXZ^2
    return new_coef, new_vars

# Function to convert the parsed terms back to a string format
def term_to_string(coef, vars):
    #coef: 2
    #vars: {X:1,Y:2}
    #return 2*XY^2
    if coef == 0:
        return ""
    
    # 1. vars
    var_str = ""
    for var, exp in sorted(vars.items()): #sorted the pairs(var:power) by alphabet
        if exp == 1:
            var_str += var
        else:
            var_str += f"{var}^{exp}"
    
    # 2. coef
    if coef == 1 and var_str:
        return var_str
    elif coef == -1 and var_str:
        return f"-{var_str}"
    else:
        return f"{coef}*{var_str}" if var_str else f"{coef}"

# Function to multiply multiple polynomials
def multiply_polynomials(polynomials):
    # Start with the first polynomial
    #key: an empty tuple(a term, ex. ((X,1),(Y,2)) XY^2); value: 1 (coefficient)
    result_terms = {(): 1}  #the result starting with 1
    
    #polynomials: all the (?????)
    #poly: each (?????), that is a string in a pair of parentheses()
    poly_counter = 0 #for debugging
    for poly in polynomials: 
        #parse a poly to a list of terms
        poly_terms = parse_polynomial(poly)
        #print(f"poly terms {poly_counter}: {poly_terms}")
        #the new terms generated by the multiplication of previous result and current poly
        new_result_terms = {}
        
        #iterate by each key, that is each result_term is a tuple
        result_terms_counter = 0
        for result_term in result_terms:
            #print(f"   result_term {result_terms_counter}: {result_term}")
            #multiply each term in current poly with the current result term from result_terms
            term_counter = 0
            for term in poly_terms:
                #print(f"     term {term_counter}: {term}")
                #multiply 2 terms
                #term_to_string(coef, vars)
                #dict(result_term): turn the tuple to a dict
                #ex. result_term == [('X', 1), ('Y', 2)] -> dict(result_term) ==  {'X': 1, 'Y': 2}
                coef, vars = multiply_terms(term, term_to_string(result_terms[result_term], dict(result_term))) 
                
                #sort key(vars is a dict) for a result by multiplying two terms
                multiplied_key = tuple(sorted(vars.items()))
                
                if multiplied_key in new_result_terms:
                    #already existed
                    new_result_terms[multiplied_key] += coef
                else:
                    #new one(tuple)
                    new_result_terms[multiplied_key] = coef
                
                term_counter += 1

            result_terms_counter += 1
        
        #"(current result terms)(poly2)"(ploy3)....
        #already finished the MUL for "(current result terms)" with a poly
        #so, copy the new result to the old one => (current result terms)(ploy3)....
        result_terms = new_result_terms
        #check a result_terms: if a value of a key is zero, remove this pair
        result_terms =  {k: v for k, v in result_terms.items() if v != 0}
        #print(f"   result_terms: {result_terms}")
        #go to next iteration, MUL for "(current result terms)" with the next poly
        poly_counter += 1
    
    #finish all the MULs, return the format needed
    #result_terms: dict, {((X,1),(Y,2)):2, ...} that is, 2*XY^2 + ...
    result = ""
    for vars, coef in result_terms.items():
        term_str = term_to_string(coef, dict(vars))
        if term_str:
            if (result != "") and (term_str[0] != "-"):
                result += "+"
            result += term_str
    
    return result

#convert the bonus input to the standard one
def bonus_convert_to_standard(input_str):
    result = ""
    input_length = len(input_str)
    can_add_coef = True # avoid: X2Y4 -> X^2*Y^4

    #iterate each char in the input
    for i in range(input_length):
        current_char = input_str[i]
        if current_char.isalpha():
            #check *
            if (i > 0) and (input_str[i-1].isdigit()) and can_add_coef:
                result = result + "*"

            result = result + current_char
            can_add_coef = False

            #check "^"
            if (i < input_length - 1) and (input_str[i+1].isdigit()):
                result = result + "^"
        else:
            result = result + current_char
            if current_char == '+' or current_char == '-' or current_char == '(':
                # the next char might be digits -> coef
                can_add_coef = True
    #print(result)
    return result

#convert a standard output to a bonus one
def bonus_ouput(str):
    result = str.replace("^","")
    result = result.replace("*","")
    return result

# Main function to do p1
def polynomial_multiplication():
    input_str = input("Input the polynomials: ")
    input_str = input_str.replace(" ", "")
    input_str = bonus_convert_to_standard(input_str)
    
    # Remove the outer parentheses and split by the ")*("
    # Removes the outer parentheses(the first and last char) from the input.
    input_str = input_str[1:-1]
    polynomials = input_str.split(")(")
    
    # Multiply all the polynomials
    result = multiply_polynomials(polynomials)
    
    #print the result
    print(f"Output Result: {result}")
    #print the bonus result
    print(f"Output Result: {bonus_ouput(result)} (bonus)")

# call the function to do p1
polynomial_multiplication()

#inputs
'''
(X+2*Y)(2*X^2-Y^2+Z)
(X+2Y)(2X2-Y2+Z)
Output Result: 2*X^3-XY^2+XZ+4*X^2Y-2*Y^3+2*YZ
Output Result: 2X3-XY2+XZ+4X2Y-2Y3+2YZ (bonus)

(2*X+3*Y+4*Z)(XY^2+X^2Y+Z^2)
(2X+3Y+4Z)(XY2+X2Y+Z2)
Output Result: 5*X^2Y^2+2*X^3Y+2*XZ^2+3*XY^3+3*YZ^2+4*XY^2Z+4*X^2YZ+4*Z^3
Output Result: 5X2Y2+2X3Y+2XZ2+3XY3+3YZ2+4XY2Z+4X2YZ+4Z3 (bonus)

(A+2*B^2)(B+3*C^3)(2*A+B+C)
(A+2B2)(B+3C3)(2A+B+C)
Output Result: 2*A^2B+AB^2+ABC+6*A^2C^3+3*ABC^3+3*AC^4+4*AB^3+2*B^4+2*B^3C+12*AB^2C^3+6*B^3C^3+6*B^2C^4
Output Result: 2A2B+AB2+ABC+6A2C3+3ABC3+3AC4+4AB3+2B4+2B3C+12AB2C3+6B3C3+6B2C4 (bonus)

(X^2+Y)(X+Y)
(X2+Y)(X+Y)
Output Result: X^3+X^2Y+XY+Y^2
Output Result: X3+X2Y+XY+Y2 (bonus)

(X+1)(X+5)
Output Result: X^2+6*X+5
Output Result: X2+6X+5 (bonus)

(X^2+1)(X+Y)
(X2+1)(X+Y)
Output Result: X^3+X^2Y+X+Y
Output Result: X3+X2Y+X+Y (bonus)

(X+2)(X^2+3*X+1)
(X+2)(X2+3X+1)
Output Result: X^3+5*X^2+7*X+2
Output Result: X3+5X2+7X+2 (bonus)

(A^3+B^2)(A^2+C)
(A3+B2)(A2+C)
Output Result: A^5+A^3C+A^2B^2+B^2C
Output Result: A5+A3C+A2B2+B2C (bonus)

(55*Z-31*X^12)(2*Y^2+70)
(55Z-31X12)(2Y2+70)
Output Result: 110*Y^2Z+3850*Z-62*X^12Y^2-2170*X^12
Output Result: 110Y2Z+3850Z-62X12Y2-2170X12 (bonus)

(X)(X-Y^5)(8*X+Z)(9*Z^2)
(X)(X-Y5)(8X+Z)(9Z2)
Output Result: 72*X^3Z^2+9*X^2Z^3-72*X^2Y^5Z^2-9*XY^5Z^3
Output Result: 72X3Z2+9X2Z3-72X2Y5Z2-9XY5Z3 (bonus)
'''

